import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: "#f4f0e8" },
  header: { padding: 24, borderBottomWidth: 1, borderBottomColor: "#c9c4b9" },
  overline: {
    color: "#bd4e32",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 2,
  },
  title: { color: "#17221d", fontSize: 34, fontWeight: "700", marginTop: 5 },
  tabs: { flexDirection: "row", gap: 20, marginTop: 24 },
  tab: { color: "#65706a", fontSize: 15 },
  activeTab: { color: "#bd4e32", fontWeight: "700", fontSize: 15 },
  notice: { backgroundColor: "#f3d9c8", marginTop: 20, padding: 12 },
  dismiss: { color: "#7e2f21", textDecorationLine: "underline", marginTop: 4 },
  intro: { paddingTop: 52, paddingHorizontal: 16, paddingBottom: 28 },
  eyebrow: {
    color: "#bd4e32",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 2,
    marginBottom: 12,
  },
  heading: {
    color: "#17221d",
    fontSize: 34,
    fontWeight: "700",
    lineHeight: 38,
  },
  list: { padding: 16, gap: 14 },
  card: {
    backgroundColor: "#fffdf8",
    borderWidth: 1,
    borderColor: "#ddd7ca",
    padding: 18,
  },
  cardImage: { width: "100%", height: 150, marginBottom: 14 },
  section: {
    color: "#bd4e32",
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  cardTitle: {
    color: "#17221d",
    fontSize: 23,
    fontWeight: "700",
    marginTop: 10,
  },
  summary: { color: "#65706a", lineHeight: 21, marginVertical: 10 },
  button: {
    alignSelf: "flex-start",
    backgroundColor: "#17221d",
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  savedButton: { backgroundColor: "#bd4e32" },
  heart: { color: "#fffdf8", fontSize: 22 },
  error: { backgroundColor: "#f3d9c8", color: "#7e2f21", padding: 12 },
  empty: { color: "#65706a", padding: 20 },
  search: {
    marginHorizontal: 16,
    marginTop: 16,
    backgroundColor: "#fffdf8",
    borderWidth: 1,
    borderColor: "#c9c4b9",
    padding: 12,
    color: "#17221d",
  },
  noteLabel: { color: "#65706a", fontSize: 12, marginBottom: 4 },
  note: {
    backgroundColor: "#f4f0e8",
    borderBottomWidth: 1,
    borderBottomColor: "#c9c4b9",
    padding: 8,
    marginBottom: 12,
    color: "#17221d",
  },
  showMore: {
    alignSelf: "center",
    backgroundColor: "#17221d",
    paddingVertical: 12,
    paddingHorizontal: 20,
    marginVertical: 8,
  },
  showMoreText: { color: "#fffdf8", fontWeight: "700" },
  savedNote: {
    color: "#bd4e32",
    fontSize: 12,
    fontStyle: "italic",
    marginTop: 8,
  },
});
